#!/usr/bin/env node
/**
 * gen-behaviour.ts — turns each skill's authored eval set into a
 * `claude plugin eval` case tree.
 *
 * The eval set is authored once, in tests/skills/<name>/evals.ts, next to the
 * contract test. The case tree it generates is committed so it is reviewable
 * in a diff, and `--check` fails when the tree has drifted from its source —
 * a generated tree nobody can trust is a generated tree nobody reads.
 *
 *   node scripts/testkit/gen-behaviour.ts            regenerate
 *   node scripts/testkit/gen-behaviour.ts --check    fail if the tree is stale
 *
 * SPDX-License-Identifier: Apache-2.0
 */

import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";

import { repoRoot, skillNames } from "./repo.ts";

/* ------------------------------------------------------------------ */
/* The authored shape                                                  */
/* ------------------------------------------------------------------ */

/** Grader types `claude plugin eval` accepts, with the fields each one takes. */
export type Grader =
  | { name: string; type: "regex"; pattern: string; target?: string; flags?: string; match?: string; weight?: number; arm?: Arm }
  | { name: string; type: "tool_used"; tool: string; input_match?: string; min?: number; max?: number; weight?: number; arm?: Arm }
  | { name: string; type: "tool_order"; before: string; after: string; weight?: number; arm?: Arm }
  | { name: string; type: "file_exists"; path: string; exists?: boolean; weight?: number; arm?: Arm }
  | { name: string; type: "llm"; criteria: string; focus?: string; weight?: number; arm?: Arm };

/**
 * `with-only` graders score the with-plugin arm alone. A `tool_used: Skill`
 * grader must carry it: the baseline arm has no skill to fire, so scoring it
 * there marks the baseline down for the plugin's absence and inflates Δ.
 */
export type Arm = "with-only" | "both";

export interface EvalCase {
  /** Directory name under behaviour/. */
  name: string;
  description: string;
  tags?: string[];
  /** The user turn. This is the whole point of the case. */
  prompt: string;
  runs?: number;
  maxTurns?: number;
  timeoutSeconds?: number;
  allowedTools?: string[];
  graders: Grader[];
}

export interface EvalSet {
  skill: string;
  cases: EvalCase[];
}

export const DEFAULTS = {
  runs: 2,
  maxTurns: 8,
  timeoutSeconds: 300,
  allowedTools: ["Read", "Glob", "Grep", "Skill"],
} as const;

/* ------------------------------------------------------------------ */
/* Emitting                                                            */
/* ------------------------------------------------------------------ */

function yamlScalar(value: unknown): string {
  if (typeof value === "number" || typeof value === "boolean") return String(value);
  const text = String(value);
  // Quote anything that a YAML reader could take for something else.
  if (text === "" || /^[\s>|&*!%@`"'{}[\],#?:-]|[:#]\s|\s$|^\d+(\.\d+)?$|^(true|false|null|yes|no|on|off)$/i.test(text)) {
    return `"${text.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
  }
  return text;
}

function yamlFrontmatter(fields: Record<string, unknown>): string {
  const lines: string[] = ["---"];
  for (const [key, value] of Object.entries(fields)) {
    if (value === undefined) continue;
    if (Array.isArray(value)) lines.push(`${key}: [${value.map(yamlScalar).join(", ")}]`);
    else lines.push(`${key}: ${yamlScalar(value)}`);
  }
  lines.push("---", "");
  return lines.join("\n");
}

const GENERATED_NOTE = (source: string) =>
  `<!-- Generated by scripts/testkit/gen-behaviour.ts from ${source}. Do not edit; edit the source and re-run \`npm run test:behaviour:gen\`. -->`;

/** Every file one case produces, keyed by path relative to the repo root. */
function renderCase(skill: string, evalCase: EvalCase): Map<string, string> {
  const files = new Map<string, string>();
  const dir = join("tests", "skills", skill, "behaviour", evalCase.name);
  const source = `tests/skills/${skill}/evals.ts`;

  files.set(
    join(dir, "prompt.md"),
    yamlFrontmatter({
      name: `${skill}/${evalCase.name}`,
      description: evalCase.description,
      tags: [...(evalCase.tags ?? []), skill],
      runs: evalCase.runs ?? DEFAULTS.runs,
      max_turns: evalCase.maxTurns ?? DEFAULTS.maxTurns,
      timeout_seconds: evalCase.timeoutSeconds ?? DEFAULTS.timeoutSeconds,
      allowed_tools: evalCase.allowedTools ?? [...DEFAULTS.allowedTools],
    }) +
      `${GENERATED_NOTE(source)}\n\n${evalCase.prompt.trim()}\n`,
  );

  for (const grader of evalCase.graders) {
    const { name, ...rest } = grader;
    // llm takes its criteria from the body; regex takes its pattern there.
    let body = "";
    const fields: Record<string, unknown> = { ...rest };
    if (grader.type === "llm") {
      body = grader.criteria.trim();
      delete fields.criteria;
    } else if (grader.type === "regex") {
      body = grader.pattern;
      delete fields.pattern;
    }
    files.set(
      join(dir, "graders", `${name}.md`),
      yamlFrontmatter(fields) + (body ? `${body}\n` : ""),
    );
  }

  return files;
}

/* ------------------------------------------------------------------ */
/* Driving                                                             */
/* ------------------------------------------------------------------ */

export async function loadEvalSets(): Promise<EvalSet[]> {
  const sets: EvalSet[] = [];
  for (const name of skillNames()) {
    const source = join(repoRoot, "tests", "skills", name, "evals.ts");
    if (!existsSync(source)) continue;
    const module = (await import(source)) as { evals?: EvalSet };
    if (!module.evals) throw new Error(`${relative(repoRoot, source)}: does not export \`evals\``);
    if (module.evals.skill !== name) {
      throw new Error(`${relative(repoRoot, source)}: declares skill "${module.evals.skill}" but sits under "${name}"`);
    }
    sets.push(module.evals);
  }
  return sets;
}

export async function renderAll(): Promise<Map<string, string>> {
  const files = new Map<string, string>();
  for (const set of await loadEvalSets()) {
    const seen = new Set<string>();
    for (const evalCase of set.cases) {
      if (seen.has(evalCase.name)) throw new Error(`${set.skill}: two eval cases named "${evalCase.name}"`);
      seen.add(evalCase.name);
      for (const [path, content] of renderCase(set.skill, evalCase)) files.set(path, content);
    }
  }
  return files;
}

/** Every file currently on disk under a behaviour/ tree. */
function existingFiles(): string[] {
  const found: string[] = [];
  for (const name of skillNames()) {
    const dir = join(repoRoot, "tests", "skills", name, "behaviour");
    if (!existsSync(dir)) continue;
    const walk = (current: string) => {
      for (const entry of readdirSync(current, { withFileTypes: true })) {
        const full = join(current, entry.name);
        if (entry.isDirectory()) walk(full);
        else if (entry.isFile() && entry.name !== ".DS_Store") found.push(relative(repoRoot, full));
      }
    };
    walk(dir);
  }
  return found.sort();
}

export interface Drift {
  missing: string[];
  stale: string[];
  changed: string[];
}

export async function drift(): Promise<Drift> {
  const expected = await renderAll();
  const onDisk = new Set(existingFiles());
  const missing: string[] = [];
  const changed: string[] = [];

  for (const [path, content] of expected) {
    if (!onDisk.has(path)) missing.push(path);
    else if (readFileSync(join(repoRoot, path), "utf8") !== content) changed.push(path);
  }
  const stale = [...onDisk].filter((p) => !expected.has(p));
  return { missing: missing.sort(), stale: stale.sort(), changed: changed.sort() };
}

async function write(): Promise<number> {
  for (const name of skillNames()) {
    const dir = join(repoRoot, "tests", "skills", name, "behaviour");
    if (existsSync(dir)) rmSync(dir, { recursive: true });
  }
  const files = await renderAll();
  for (const [path, content] of files) {
    const full = join(repoRoot, path);
    mkdirSync(join(full, ".."), { recursive: true });
    writeFileSync(full, content);
  }
  return files.size;
}

async function main(): Promise<number> {
  const check = process.argv.includes("--check");
  if (!check) {
    const count = await write();
    console.log(`Wrote ${count} file(s) across ${(await loadEvalSets()).length} skill eval set(s).`);
    return 0;
  }

  const result = await drift();
  const total = result.missing.length + result.stale.length + result.changed.length;
  if (total === 0) {
    console.log("Behaviour case tree matches its source.");
    return 0;
  }
  console.error("Behaviour case tree has drifted from tests/skills/*/evals.ts:");
  for (const path of result.missing) console.error(`  missing  ${path}`);
  for (const path of result.changed) console.error(`  changed  ${path}`);
  for (const path of result.stale) console.error(`  stale    ${path}`);
  console.error("\nRun `npm run test:behaviour:gen` and commit the result.");
  return 1;
}

if (import.meta.filename === process.argv[1]) {
  process.exit(await main());
}
